version: '3.8'

services:
  frontend:
    build: ./frontend
    image: colorgame-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: colorgame-backend:latest
    ports:
      - "8080:8080" 