version: '3.8'

services:
  frontend:
    build: ./frontend
    image: colorgame-frontend:latest
    ports:
      - "80:80"
    environment:
      - VUE_APP_WS_URL=ws://backend:8080/api/game/ws
    depends_on:
      - backend

  backend:
    build: ./backend
    image: colorgame-backend:latest
    ports:
      - "8080:8080" 