name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      
    - name: Build Docker images
      run: |
        docker compose build
        docker save $(docker images -q) -o images.tar
        
    - name: Debug SSH setup
      run: |
        echo "Setting up SSH configuration..."
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        ls -la ~/.ssh/private.key
        echo "SSH key permissions set"
        
        # 測試 SSH 連接
        ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no -vvv ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} 'echo "SSH connection successful"'
        
    - name: Copy files to EC2
      run: |
        echo "Copying files to EC2..."
        scp -i ~/.ssh/private.key -o StrictHostKeyChecking=no images.tar docker-compose.yml ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:~/colorgame/
        
    - name: Deploy to EC2
      run: |
        echo "Starting deployment..."
        ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} '
          cd ~/colorgame &&
          docker load < images.tar &&
          docker compose down &&
          docker compose up -d &&
          rm images.tar
        ' 