name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and save Docker images
      run: |
        docker-compose build
        docker save colorgame-frontend:latest > frontend.tar
        docker save colorgame-backend:latest > backend.tar
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        
    - name: Copy Docker images to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "*.tar,docker-compose.yml"
        target: "~/colorgame"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/colorgame
          docker load < frontend.tar
          docker load < backend.tar
          docker-compose down
          docker-compose up -d
          rm *.tar 