name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      
    - name: Build Docker images
      run: |
        docker compose build
        docker save $(docker images -q) -o images.tar
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        cat >>~/.ssh/config <<END
        Host aws
          HostName ${{ secrets.AWS_HOST }}
          User ${{ secrets.AWS_USERNAME }}
          IdentityFile ~/.ssh/private.key
          StrictHostKeyChecking no
        END
        
    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/private.key images.tar docker-compose.yml ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:~/colorgame/
        
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/private.key ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} '
          cd ~/colorgame &&
          docker load < images.tar &&
          docker compose down &&
          docker compose up -d &&
          rm images.tar
        ' 