name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      
    - name: Build Docker images
      run: |
        docker compose build
        docker save $(docker images -q) -o images.tar
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        
        # 添加主機到 known_hosts
        ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        
        # 創建 SSH 配置文件
        cat > ~/.ssh/config << EOF
        Host ec2
          HostName ${{ secrets.AWS_HOST }}
          User ${{ secrets.AWS_USERNAME }}
          IdentityFile ~/.ssh/private.key
          StrictHostKeyChecking no
          UserKnownHostsFile ~/.ssh/known_hosts
        EOF
        
        chmod 600 ~/.ssh/config
        chmod 600 ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: ssh ec2 'echo "SSH connection successful"'
        
    - name: Copy files to EC2
      run: |
        echo "Copying files to EC2..."
        scp -i ~/.ssh/private.key images.tar docker-compose.yml ec2:~/colorgame/
        
    - name: Deploy to EC2
      run: |
        echo "Starting deployment..."
        ssh ec2 '
          cd ~/colorgame &&
          docker load < images.tar &&
          docker compose down &&
          docker compose up -d &&
          rm images.tar
        ' 