name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 獲取完整的 git 歷史
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: |
        # 強制重新構建，不使用緩存
        docker compose build --no-cache
        docker save $(docker images -q) -o images.tar
        
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private.key
        chmod 600 ~/.ssh/private.key
        ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        
        cat > ~/.ssh/config << EOF
        Host ec2
          HostName ${{ secrets.AWS_HOST }}
          User ${{ secrets.AWS_USERNAME }}
          IdentityFile ~/.ssh/private.key
          StrictHostKeyChecking no
          UserKnownHostsFile ~/.ssh/known_hosts
        EOF
        
        chmod 600 ~/.ssh/config
        chmod 600 ~/.ssh/known_hosts
        
    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        cp docker-compose.yml deploy/
        cp -r frontend deploy/
        cp -r backend deploy/
        tar czf deploy.tar.gz deploy/
        
    - name: Copy files to EC2
      run: |
        echo "Copying files to EC2..."
        scp -i ~/.ssh/private.key images.tar deploy.tar.gz ec2:~/colorgame/
        
    - name: Deploy to EC2
      run: |
        echo "Starting deployment..."
        ssh ec2 '
          cd ~/colorgame &&
          tar xzf deploy.tar.gz &&
          rm -rf frontend backend docker-compose.yml &&  # 強制移除舊文件
          mv deploy/* . &&
          rm -rf deploy deploy.tar.gz &&
          docker load < images.tar &&
          # 強制移除所有容器和映像
          docker compose down --remove-orphans || true &&
          docker system prune -af &&  # 強制清理所有未使用的資源
          # 強制重新拉取和啟動
          docker compose pull --ignore-pull-failures &&
          docker compose up -d --force-recreate &&
          rm images.tar
        ' 